"""creating missing columns by using the models.py and autogenerate feature

Revision ID: da1017462ceb
Revises: 3f4a07d5b35e
Create Date: 2023-03-05 21:26:53.580018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1017462ceb'
down_revision = '3f4a07d5b35e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
